version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgre
      - DATABASE_NAME=BookNYT
      - DATABASE_USERNAME=postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_DB=BookNYT
    ports:
      - "5432:5432" 
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

































#WORKS BUT CANT GET DB

# version: "3"

# services:
#   api:
#     build: .
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#     volumes:
#       - .:/usr/src/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres:15.0-alpine

#     environment:
#       # - DATABASE_HOSTNAME=postgres
#       # - DATABASE_PORT=5432
#       # - DATABASE_PASSWORD=postgre
#       # - DATABASE_NAME=BookNYT
#       # - DATABASE_USERNAME=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgre
#       - POSTGRES_DB=BookNYT
      
























